// src/index.ts
//
// bauspar-engine -- OCM run 3 target observation of unit U01.
//
// Launch interface (GR-14, target directive 4): the program demands exactly one
// input path -- the contract table -- as a de-quoted command-line argument. A
// second optional argument names the valuation date; absent, it is read from the
// input manifest. No display capability is probed, because at CORE tier there is
// no user interface to probe one for (R17 would otherwise apply).
//
// Everything else is optional and has a default:
//   --manifest <path>       the input manifest, if it is not beside the table
//   --evidence-dir <path>   where the bundle is written
//   --run-id <id>           the run identifier carried in the artifacts
//   --label <name>          suffix for a second, smaller observation (the probe)
//   --emitted-utc <ts>      pin the timestamp, for the determinism diff
//   --selftest-only         run the self-tests and stop
//
// Order of operations is contractual, not incidental:
//   1. self-tests, including the contract's reference vectors -- the contract
//      requires the emitter to abort on mismatch, and GR-13 requires SelfTest
//      green before anything is packaged;
//   2. the io layer's own content-based reading, diffed against the spec (R7);
//   3. the observation;
//   4. the preconditions;
//   5. the evidence bundle.
// A diagnostic generated by an operation cannot be reported before that
// operation runs (R16), so nothing below prints a finding it has not yet made.

import * as fs from "node:fs";
import * as path from "node:path";
import { runSelfTests, type SelfTestReport } from "./selftest.js";
import { runPipeline, type PipelineResult } from "./pipeline.js";
import { Journal } from "./logging.js";
import { DateParseAbort, renderIsoDate } from "./dates.js";
import { canonicalString, intText } from "./canonical.js";
import { fileDigest, type CheckpointObject } from "./checkpoint.js";

const RUN_ID_DEFAULT = "ocm-run-3-bauspar";

/** GR-02: Eclipse's Arguments box passes quotes through; de-quote before use. */
function dequote(s: string): string {
  if (s.length >= 2) {
    const a = s[0]!;
    const b = s[s.length - 1]!;
    if ((a === '"' && b === '"') || (a === "'" && b === "'")) return s.slice(1, s.length - 1);
  }
  return s;
}

interface Args {
  inputPath: string | null;
  valuationDate: string | null;
  manifestPath: string | null;
  evidenceDir: string;
  runId: string;
  label: string | null;
  emittedUtc: string | null;
  selfTestOnly: boolean;
}

function parseArgs(argv: string[]): Args {
  const a: Args = {
    inputPath: null, valuationDate: null, manifestPath: null,
    evidenceDir: path.join("runs", RUN_ID_DEFAULT, "evidence", "target"),
    runId: RUN_ID_DEFAULT, label: null, emittedUtc: null, selfTestOnly: false,
  };
  const positional: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    const t = argv[i]!;
    if (t === "--selftest-only") { a.selfTestOnly = true; continue; }
    if (t === "--manifest") { a.manifestPath = dequote(argv[++i] ?? ""); continue; }
    if (t === "--evidence-dir") { a.evidenceDir = dequote(argv[++i] ?? ""); continue; }
    if (t === "--run-id") { a.runId = dequote(argv[++i] ?? ""); continue; }
    if (t === "--label") { a.label = dequote(argv[++i] ?? ""); continue; }
    if (t === "--emitted-utc") { a.emittedUtc = dequote(argv[++i] ?? ""); continue; }
    if (t.startsWith("--")) {
      throw new Error("unknown option " + JSON.stringify(t) + " -- this program takes one input path, an optional valuation date, and the options listed in its header");
    }
    positional.push(dequote(t));
  }
  a.inputPath = positional.length > 0 ? positional[0]! : null;
  a.valuationDate = positional.length > 1 ? positional[1]! : null;
  if (positional.length > 2) {
    throw new Error(
      "too many arguments: this program demands exactly one input path and accepts one optional valuation date; " +
      "received " + intText(positional.length) + ": " + positional.join(", "),
    );
  }
  return a;
}

function utcStamp(pinned: string | null): string {
  if (pinned !== null) return pinned;
  const d = new Date();
  const p = (n: number) => (n < 10 ? "0" + intText(n) : intText(n));
  return (
    intText(d.getUTCFullYear()) + "-" + p(d.getUTCMonth() + 1) + "-" + p(d.getUTCDate()) + "T" +
    p(d.getUTCHours()) + ":" + p(d.getUTCMinutes()) + ":" + p(d.getUTCSeconds()) + "Z"
  );
}

/**
 * R12, executed rather than reviewed at this layer: no number reaches the JSON
 * except as an exact integer. Every VALUE in a checkpoint travels as canonical
 * text; the only numbers the schema admits are counts, row and column tallies
 * and epoch-free indices. A double appearing here would mean a value had
 * escaped the canonicalisation contract.
 */
function assertOnlyIntegers(node: unknown, where: string): void {
  if (typeof node === "number") {
    if (!Number.isSafeInteger(node)) {
      throw new Error("non-integer number reached the JSON at " + where + " -- a value escaped the canonicalisation contract");
    }
    return;
  }
  if (Array.isArray(node)) {
    node.forEach((v, i) => assertOnlyIntegers(v, where + "[" + intText(i) + "]"));
    return;
  }
  if (node !== null && typeof node === "object") {
    for (const [k, v] of Object.entries(node as Record<string, unknown>)) assertOnlyIntegers(v, where + "." + k);
  }
}

function writeUtf8Lf(p: string, text: string): void {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, text.split("\r\n").join("\n"), "utf8");
}

function writeJson(p: string, obj: unknown): void {
  assertOnlyIntegers(obj, path.basename(p));
  writeUtf8Lf(p, JSON.stringify(obj, null, 2) + "\n");
}

function main(): number {
  const args = parseArgs(process.argv.slice(2));
  const journal = new Journal();
  const evidenceDir = path.resolve(args.evidenceDir);
  const suffix = args.label === null ? "" : "_" + args.label;

  // ---- 1. self-tests --------------------------------------------------------
  process.stdout.write("[selftest] running self-tests at the declared language level\n");
  const st: SelfTestReport = runSelfTests(path.join(evidenceDir, "selftest_work"));
  writeJson(path.join(evidenceDir, "selftest_target" + suffix + ".json"), {
    run_id: args.runId,
    side: "target",
    passed: st.passed,
    failed: st.failed,
    groups: groupCounts(st),
    blind_spots: st.blindSpots,
    good_input_control_run: st.separation,
    checks: st.results.map((r) => ({ group: r.group, name: r.name, ok: r.ok, detail: r.detail })),
  });
  process.stdout.write(
    "[selftest] " + intText(st.passed) + " passed, " + intText(st.failed) + " failed\n",
  );
  if (st.failed > 0) {
    for (const r of st.results) if (!r.ok) process.stderr.write("[selftest FAIL] " + r.group + " / " + r.name + ": " + r.detail + "\n");
    process.stderr.write(
      "[abort] the canonicalisation contract requires the emitter to abort on a reference-vector mismatch, " +
      "and GR-13 requires SelfTest green before anything is packaged. No artifact was written.\n",
    );
    return 2;
  }
  if (args.selfTestOnly) return 0;

  if (args.inputPath === null) {
    process.stderr.write(
      "usage: bauspar-engine <contract-table.csv> [valuation-date] [--manifest p] [--evidence-dir p] [--run-id id] [--label name]\n" +
      "no input path was supplied. This program demands exactly one input path (GR-14).\n",
    );
    return 64;
  }
  if (!fs.existsSync(args.inputPath)) {
    process.stderr.write(
      "This argument did not resolve to an existing file:\n  " + args.inputPath +
      "   (no such file -- check for a typo, a moved file, or a stray quote)\n",
    );
    return 66;
  }

  const emitted = utcStamp(args.emittedUtc);

  // ---- 2-4. the observation -------------------------------------------------
  let result: PipelineResult;
  try {
    result = runPipeline({
      inputPath: args.inputPath,
      manifestPath: args.manifestPath,
      valuationDateArg: args.valuationDate,
      journal,
      compareObservational: args.label === null,
    });
  } catch (e) {
    if (e instanceof DateParseAbort) {
      return emitAbort(e, args, evidenceDir, emitted, journal);
    }
    throw e;
  }

  // ---- 5. the evidence bundle ----------------------------------------------
  // Canonicalisation contract §7: EVERY input file consumed, by name, size and
  // digest. This program consumes two: the contract table, and the input
  // manifest, whose declared harness coercions decide whether the abort path
  // fires and are therefore part of the observation contract, not incidental
  // staging (controller directive 01). Under-reporting a consumed input would
  // be exactly the silent decline R16 forbids. Names are basenames, because the
  // two sides hold the same files at different paths.
  const inputs = [
    { name: path.basename(args.inputPath), ...fileDigest(args.inputPath) },
    { name: path.basename(result.manifest.file), ...fileDigest(result.manifest.file) },
  ];
  const checkpoint = {
    run_id: args.runId,
    side: "target" as const,
    state: "OBSERVE_TARGET" as const,
    canonicalisation: "dec9-half-even-v1" as const,
    emitted_utc: emitted,
    inputs,
    units: [{ unit: "U01", objects: result.checkpointObjects as CheckpointObject[] }],
  };
  const cpPath = path.join(evidenceDir, "checkpoints_target" + suffix + ".json");
  writeJson(cpPath, checkpoint);

  writeJson(path.join(evidenceDir, "preconditions_target" + suffix + ".json"), {
    run_id: args.runId,
    side: "target",
    state: "OBSERVE_TARGET",
    emitted_utc: emitted,
    input: path.basename(args.inputPath),
    valuation_date: renderIsoDate(result.valuationDay),
    valuation_date_source: result.valuationDateSource,
    results: result.preconditions,
  });

  // The browser data file of behaviour step C24, written as the unit writes it:
  // UTF-8, each of the five parts followed by one line feed.
  writeUtf8Lf(path.join(evidenceDir, "customers_data" + suffix + ".js"), result.documentTextValue);
  process.stdout.write(
    intText(result.aggregates.rowsRead) + " contracts written to " +
    path.join(evidenceDir, "customers_data" + suffix + ".js") + "\n",
  );

  writeUtf8Lf(path.join(evidenceDir, "run_report_target" + suffix + ".md"), runReport(args, result, st, journal, emitted, "COMPLETE"));

  for (const o of result.checkpointObjects) {
    process.stdout.write(
      "[checkpoint] " + o.name + ": rows " + intText(o.rows ?? 0) + ", cols " + intText(o.cols ?? 0) +
      ", digest " + o.digest.value + "\n",
    );
  }
  return 0;
}

function groupCounts(st: SelfTestReport): Record<string, number> {
  const m: Record<string, number> = {};
  for (const r of st.results) m[r.group] = (m[r.group] ?? 0) + 1;
  return m;
}

/**
 * Controller directive 01, Rules B and C: an aborted run emits NO checkpoint
 * file and an abort_record.json instead, and keeps whatever was built before the
 * abort as a partial bundle marked incomplete. A halt is a decision handed back,
 * not a crash.
 */
function emitAbort(
  e: DateParseAbort, args: Args, evidenceDir: string, emitted: string, journal: Journal,
): number {
  const record = {
    run_id: args.runId,
    side: "target",
    state: "OBSERVE_TARGET",
    unit: "U01",
    abort_code: "DATE_PARSE_ABORT",
    row_index: e.rowIndex,
    column: e.column,
    raw_value: canonicalString(e.rawValue),
    rows_completed: e.rowIndex - 1,
  };
  writeJson(path.join(evidenceDir, "abort_record.json"), record);
  writeUtf8Lf(
    path.join(evidenceDir, "run_report_target" + (args.label === null ? "" : "_" + args.label) + ".md"),
    [
      "# Target run report -- INCOMPLETE (aborted)",
      "",
      "Run id: `" + args.runId + "`  ",
      "Input: `" + (args.inputPath ?? "") + "`  ",
      "Emitted: `" + emitted + "`",
      "",
      "## State",
      "",
      "**INCOMPLETE.** The unit's date reader aborted, and under controller directive 01 Rule B an",
      "aborted run emits NO checkpoint file: a partial checkpoint is not comparable (R12). The",
      "`abort_record.json` beside this report is what COMPARE reads instead.",
      "",
      "## The abort",
      "",
      "| field | value |",
      "|---|---|",
      "| abort_code | `DATE_PARSE_ABORT` |",
      "| row_index | " + intText(e.rowIndex) + " (1-based, in the input table as received, before any sort) |",
      "| column | `" + e.column + "` |",
      "| raw_value | `" + canonicalString(e.rawValue) + "` |",
      "| rows_completed | " + intText(e.rowIndex - 1) + " |",
      "",
      "The trigger, as the directive states it mechanically: the text contains a hyphen, is not",
      "accepted by the standard unambiguous parse, and is the first non-missing element of the vector",
      "the conversion is applied to. `" + e.column + "` is a column the unit parses ITSELF, so the unit",
      "hands the reader one value at a time and that value is always the first element of its own",
      "vector -- which is why every hyphenated unreadable value in such a column aborts, at whatever",
      "row it sits. Had the same value been placed in a harness-coerced column anywhere but the first",
      "non-missing position, it would have gone quietly missing and the run would have completed.",
      "",
      "## What was built before the abort",
      "",
      "Self-tests ran green before any row was read; their report is `selftest_target*.json`.",
      "The layout reading and the manifest were resolved. No contract record was published, because",
      "the abort stops processing immediately: the unit does not skip the row, does not substitute a",
      "missing value, and does not continue to the next contract (Rule A).",
      "",
      "## Notices raised before the abort",
      "",
      journal.notices.length === 0 ? "None." : journal.notices.map((n) => "- " + n.kind + " at " + n.where + ": " + n.what + " -- " + n.why).join("\n"),
      "",
    ].join("\n"),
  );
  process.stderr.write(
    "[abort] DATE_PARSE_ABORT at row " + intText(e.rowIndex) + ", column " + e.column +
    ", value " + JSON.stringify(e.rawValue) + "; " + intText(e.rowIndex - 1) + " rows completed. " +
    "No checkpoint file was written (controller directive 01, Rule B).\n",
  );
  return 3;
}

function runReport(
  args: Args, r: PipelineResult, st: SelfTestReport, journal: Journal, emitted: string, state: string,
): string {
  const L: string[] = [];
  L.push("# Target run report -- " + state);
  L.push("");
  L.push("Run id: `" + args.runId + "`  ");
  L.push("Input: `" + args.inputPath + "`  ");
  L.push("Input manifest: `" + r.manifest.file + "`  ");
  L.push("Valuation date: `" + renderIsoDate(r.valuationDay) + "` (source: " + r.valuationDateSource + ")  ");
  L.push("Emitted: `" + emitted + "`");
  L.push("");
  L.push("## 1. Self-tests (GR-13, R8, R18)");
  L.push("");
  L.push("- passed: **" + intText(st.passed) + "**, failed: **" + intText(st.failed) + "**");
  L.push("");
  L.push("Good-input control run (R18) -- separation between known-good and known-bad fixtures:");
  L.push("");
  for (const s of st.separation) L.push("- " + s);
  L.push("");
  L.push("Blind spots (R8):");
  L.push("");
  for (const b of st.blindSpots) L.push("- " + b);
  L.push("");
  L.push("## 2. The io layer's own reading, and the spec's claims (R7)");
  L.push("");
  L.push("Detected by content, with margins (R5):");
  L.push("");
  L.push("```");
  L.push(r.layout.note);
  L.push("```");
  L.push("");
  L.push("| id | class | claim | spec says | target reads | agree |");
  L.push("|---|---|---|---|---|---|");
  for (const c of r.claims) {
    L.push(
      "| " + c.id + " | " + (c.klass === "computation_critical" ? "**critical**" : "observational") +
      " | " + c.claim + " | " + mdCell(c.specReading) + " | " + mdCell(c.targetReading) + " | " +
      (c.agreed ? "yes" : "**NO**") + " |",
    );
  }
  L.push("");
  const dis = r.claims.filter((c) => !c.agreed);
  if (dis.length === 0) {
    L.push("Every claim agrees with the target's independent reading.");
  } else {
    L.push("**Disagreements.** None of these is computation-critical -- a critical disagreement halts");
    L.push("the run before any row is computed -- so the run continued and both readings are recorded:");
    L.push("");
    for (const c of dis) L.push("- `" + c.id + "` " + c.claim + ": spec says `" + c.specReading + "`, target reads `" + c.targetReading + "`.");
  }
  L.push("");
  L.push("## 3. Harness coercions, applied exactly as declared");
  L.push("");
  L.push("| column | declared | format inferred from | first non-missing value | row |");
  L.push("|---|---|---|---|---|");
  for (const [k, v] of r.coercions) {
    L.push("| `" + k + "` | to_date_class | " + (v.format ?? "none -- column coerces to missing") + " | " +
      (v.firstNonMissingValue === null ? "(none)" : "`" + v.firstNonMissingValue + "`") + " | " +
      (v.firstNonMissingRow < 0 ? "-" : intText(v.firstNonMissingRow)) + " |");
  }
  L.push("");
  L.push("Columns left as raw year-month-day digits (parsed by the unit itself, so every hyphenated");
  L.push("unreadable value in them aborts): `" + r.manifest.leftAsRaw.join("`, `") + "`.");
  L.push("");
  L.push("## 4. Parse reconciliation (GR-08, R16)");
  L.push("");
  L.push("- rows read: **" + intText(r.aggregates.rowsRead) + "**");
  L.push("- records published: **" + intText(r.aggregates.recordsPublished) + "**");
  L.push("- rows refused: **0**");
  L.push("");
  L.push("Notices raised, by kind and reason:");
  L.push("");
  for (const s of journal.summary()) L.push("- `" + s.key + "` x" + intText(s.count));
  if (journal.summary().length === 0) L.push("- none");
  L.push("");
  L.push("## 5. Checkpoint objects");
  L.push("");
  L.push("| object | kind | rows | cols | digest |");
  L.push("|---|---|---|---|---|");
  for (const o of r.checkpointObjects) {
    L.push("| `" + o.name + "` | " + o.kind + " | " + intText(o.rows ?? 0) + " | " + intText(o.cols ?? 0) + " | `" + o.digest.value + "` |");
  }
  L.push("");
  L.push("## 6. Preconditions");
  L.push("");
  L.push("| id | severity | status | evidence |");
  L.push("|---|---|---|---|");
  for (const p of r.preconditions) {
    L.push("| " + p.id + " | " + p.severity + " | **" + p.status + "** | " + mdCell(p.evidence) + " |");
  }
  L.push("");
  L.push("## 7. Findings policy");
  L.push("");
  L.push("FAITHFUL ONLY (target directive 13). Every defect the neutral spec records as the source's");
  L.push("behaviour is implemented as the source does it. There is no switch, no corrected variant and");
  L.push("no delta report, and GR-12/R9's switch mechanism is stood down for this run by owner decision.");
  L.push("");
  L.push("## 8. Capabilities NOT exercised");
  L.push("");
  L.push("- No artifact browser and no figure rendering: CORE tier, stood down explicitly by target directive 6 (GR-04, GR-05, GR-06).");
  L.push("- No dialog smoke test: there is no user interface, so there is no display capability to probe (GR-03, R17).");
  L.push("- No external retrieval of any kind occurred. No source-side artifact was read.");
  L.push("- The unit's load-time branches (L1-L3), single-contract inspector (C26) and standalone-page writer (C27) are not entry points of this build; their preconditions say NOT_EXERCISED rather than PASS.");
  L.push("- Run at " + intText(r.aggregates.rowsRead) + " rows. The build has NOT been run on full-size real input (45,881 rows), so GR-09's full-size gate is not discharged.");
  L.push("");
  L.push("## 9. Scale note (R11, GR-09)");
  L.push("");
  L.push("Both passes stream the file in 64 KiB blocks and keep column-oriented typed arrays, never a");
  L.push("table of parsed row objects. Memory is a fixed cost per cell: 8 bytes for a numeric or date");
  L.push("column, 1 byte for a logical column. The document object holds one string per line, which is");
  L.push("inherent to what it is.");
  L.push("");
  return L.join("\n") + "\n";
}

function mdCell(s: string): string {
  const t = s.split("|").join("\\|").split("\n").join(" ");
  return t.length > 600 ? t.slice(0, 597) + "..." : t;
}

try {
  process.exit(main());
} catch (e) {
  process.stderr.write("[error] " + (e instanceof Error ? e.message : String(e)) + "\n");
  if (e instanceof Error && e.stack) process.stderr.write(e.stack + "\n");
  process.exit(1);
}
