// src/script.ts
//
// Neutral spec behaviour steps C22, C23 and C24 -- the browser data file.
//
// The rendering rule here is NOT the rule of C20 and NOT the canonicalisation
// contract's 9-significant-digit rule. It is the ordinary C fixed-format "%.6f"
// conversion, half-even on the exact binary value, with trailing zeros and then
// a trailing decimal point removed. Using one rule for both WILL diverge; the
// spec says so and the self-tests check both against their own vectors.
//
// Note the deliberate asymmetry of C24: the identifier used as the entry KEY has
// only its double quotes escaped -- a backslash in it is NOT escaped -- while the
// same identifier rendered as the `id` VALUE goes through the full C22 text rule
// and has its backslashes doubled. That is the source's behaviour.

import { scriptNumber, scriptString } from "./canonical.js";
import { EXPORT_FIELDS, type ExportValue } from "./engine.js";
import { intText } from "./canonical.js";
import { renderIsoDate } from "./dates.js";

export const BROWSER_FILE_FIRST_LINE = "// customers_data.js  --  generated by customer_engine.R";
export const BROWSER_FILE_OPEN_LINE = "window.CUSTOMERS = {";
export const BROWSER_FILE_CLOSE_LINE = "};";

/** Behaviour step C22, applied to one exported value. */
export function renderScriptValue(v: ExportValue | boolean): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) return "null";
    return scriptNumber(v);
  }
  return scriptString(v);
}

/** Behaviour step C23: one contract as a brace-wrapped list of the 25 names. */
export function renderScriptRecord(values: ExportValue[]): string {
  let out = "{";
  for (let i = 0; i < EXPORT_FIELDS.length; i++) {
    if (i > 0) out += ",";
    out += '"' + EXPORT_FIELDS[i]! + '":' + renderScriptValue(values[i]!);
  }
  return out + "}";
}

/**
 * Behaviour step C24, identifier escaping for the entry KEY: only the double
 * quote is escaped. A backslash is left as it stands.
 */
export function escapeEntryKey(id: string | null): string {
  // A missing identifier renders through the source language's default
  // text conversion, which yields the two letters N A. Not exercised by the
  // stand-in (every row carries an identifier); recorded as an ambiguity.
  const s = id === null ? "NA" : id;
  let out = "";
  for (let i = 0; i < s.length; i++) {
    if (s.charCodeAt(i) === 0x22) out += '\\"';
    else out += s[i];
  }
  return out;
}

export function renderEntry(id: string | null, values: ExportValue[]): string {
  return '"' + escapeEntryKey(id) + '":' + renderScriptRecord(values);
}

/**
 * Behaviour step C24, the five parts of the file, as PHYSICAL LINES.
 * For a table of n rows the document has n + 4 lines. The file itself is those
 * lines each followed by one line feed, so it ends with a line feed.
 */
export function documentLines(entries: string[], rowCount: number, valuationDay: number): string[] {
  const lines: string[] = [];
  lines.push(BROWSER_FILE_FIRST_LINE);
  lines.push("// " + intText(rowCount) + " contracts, valuation date " + renderIsoDate(valuationDay));
  lines.push(BROWSER_FILE_OPEN_LINE);
  for (let i = 0; i < entries.length; i++) {
    lines.push(entries[i]! + (i === entries.length - 1 ? "" : ","));
  }
  lines.push(BROWSER_FILE_CLOSE_LINE);
  return lines;
}

export function documentText(lines: string[]): string {
  return lines.join("\n") + "\n";
}
